### ISSUE TITLE
[Demo] List of tasks

### ISSUE THREAD

**Issue by badabam** [badabam/web-hh-22-3-todo-app-board-test#1]
## Value proposition
**As a** user,
**I want to** create a list of tasks
**so that** I don't have to remember them

## Description

<img src=https://user-images.githubusercontent.com/157286/174497638-95c949f5-9b38-49bf-94e9-b7ac90adcd64.png width=320px>

## Acceptance criteria
- [ ] Items are added to the end
- [ ] The form is always at the bottom
- [ ] Todos scroll above the form
- [ ] Whitespace is trimmed
- [ ] Empty todos are not added
- [ ] Items wrap
- [ ] Maxlength is 100 chars

## Complexity
Small | Medium | Large

## Tasks
- [x] Create branch
- [x] Add base styles
- [x] Storybook for TodoForm components
- [x] TodoForm component
- [x] TodoForm tests
- [x] Add TodoForm to App
- [x] Add list of todos
