### ISSUE TITLE
[Demo] Checkboxes

### ISSUE THREAD

**Issue by badabam** [badabam/web-hh-22-3-todo-app-board-test#2]
## Value proposition
**As a** user,
**I want to** check and uncheck tasks
**so that** I have an overview of what i've done

## Description

<img src=https://user-images.githubusercontent.com/157286/174502125-035adb02-a4ca-40e9-bf24-7f4877f8d50c.png width=320px>

## Acceptance criteria
- [ ] todos are created unchecked
- [ ] todos don't change order
- [ ] click on todo checks it
- [ ] checked todos are striked through

## Complexity
Small

## Tasks
- [x] Create branch
- [x] Add storybook for component TodoItem
- [x] Implement component TodoItem
- [x] Write specs for TodoItem
- [x] Update App with TodoItem
