### ISSUE TITLE
[Demo] Add backend

### ISSUE THREAD

**Issue by badabam** [badabam/web-hh-22-3-todo-app-board-test#3]
## Value proposition
**As a** user,
**I want to** have my data on a server
**so that** I can access it from multiple devices

## Description
No visual change

## Acceptance criteria
- [ ] Todos are persisted in backend
- [ ] Screen shows "... Loading ..." while loading
- [ ] New todos are rendered when the backend answered with success
- [ ] (later) New todos are added optimistically and updated after server response

## Complexity
Medium

## Tasks
- [ ] Create branch
- [ ] Install useSWR
- [ ] Fetch data on initial run
- [ ] Refetch on focus
